let s=CafeDemo.seed(),ready=false,busy=false,revision=0,storageError='',tab='Venta',cart={},selected='a',filter='pending',group='all',mode='cash',saleToken=null,paymentToken=null,doc=null;
const $=id=>document.getElementById(id),money=n=>new Intl.NumberFormat('es-MX',{style:'currency',currency:s.config.currency}).format(n/100),esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),token=()=>Math.random().toString(36).slice(2)+Date.now().toString(36);
function note(t){$('toast').textContent=t}function saldo(n){return n>0?money(n)+' por pagar':n<0?money(-n)+' a favor':'Al corriente'}function student(){return s.students.find(a=>a.id===selected)}function items(){return s.products.filter(p=>cart[p.id]).map(p=>({...p,qty:cart[p.id]}))}function amount(){return items().reduce((n,p)=>n+p.price*p.qty,0)}
function nav(to){if(!ready||busy)return;if(!s.config.initialized&&to!=='Ajustes'){note('Primero guarda la configuración de la cafetería.');return;}tab=to;doc=null;note('');render()}function button(text,action,style=''){return `<button class="${style}" onclick="${action}">${text}</button>`}function title(k,t){return `<span class="eyebrow">${k}</span><h1>${t}</h1>`}
function render(){if(!ready)return;const names=['Venta','Cuentas','Alumnos','Menú','Reportes','Ajustes'];$('nav').innerHTML=names.map(n=>button(n,`nav('${n}')`,tab===n||['Cuenta','Pago','Documento'].includes(tab)&&n==='Cuentas'?'active':'')).join('');$('screen').innerHTML=({Venta:saleScreen,Cuentas:accountsScreen,Cuenta:accountScreen,Pago:paymentScreen,Documento:documentScreen,Alumnos:studentsScreen,Menú:menuScreen,Reportes:reportsScreen,Ajustes:settingsScreen})[tab]();}
function saleScreen(){return title('Durante el despacho','Nueva venta')+`<p class="muted">Toca un producto para agregarlo.</p><div class="products">${s.products.map(p=>`<button class="product" onclick="add('${p.id}',1)"><strong>${esc(p.name)}</strong><span>${money(p.price)}</span></button>`).join('')}</div><div class="card"><h2>Esta compra</h2>${items().map(p=>`<div class="row"><div>${esc(p.name)}<br><span class="muted">${money(p.price)} cada uno</span></div><div class="qty">${button('−',`add('${p.id}',-1)`)}<strong>${p.qty}</strong>${button('+',`add('${p.id}',1)`)}</div></div>`).join('')||'<p class="muted">Todavía no hay productos.</p>'}<div class="row"><strong>Total</strong><span class="total">${money(amount())}</span></div></div><button class="full" onclick="prepareSale()" ${!amount()?'disabled':''}>Continuar · Elegir cómo registrar</button>`;}
function add(id,n){if(!ready||busy)return;cart[id]=Math.max(0,(cart[id]||0)+n);render()}
function prepareSale(){if(!ready||busy||!amount())return;saleToken=token();mode='cash';showSaleConfirmation()}
function showSaleConfirmation(){const a=student(),prior=a?CafeDemo.balance(s,selected):0;$('screen').innerHTML=title('Revisar antes de guardar','Confirmar venta')+`<div class="card"><span class="muted">Total de la compra</span><div class="bigbalance">${money(amount())}</div>${items().map(p=>`<div class="row"><span>${p.qty} × ${esc(p.name)}</span><strong>${money(p.qty*p.price)}</strong></div>`).join('')}</div><label>¿Cómo se registra?</label><select id="saleMode" onchange="mode=this.value;showSaleConfirmation()"><option value="cash" ${mode==='cash'?'selected':''}>Pagado ahora</option><option value="sale" ${!s.students.length?'disabled':''} ${mode==='sale'?'selected':''}>A la cuenta del alumno</option></select>${mode==='sale'?`<label>Alumno</label><select onchange="selected=this.value;showSaleConfirmation()">${s.students.map(x=>`<option value="${x.id}" ${selected===x.id?'selected':''}>${esc(x.name)} · ${esc(x.group)}</option>`).join('')}</select><div class="card"><div class="row"><span>Antes de esta compra</span><strong>${saldo(prior)}</strong></div><div class="row"><span>Después</span><strong>${saldo(prior+amount())}</strong></div></div><p class="muted">Se usa el saldo a favor existente. No se registra otro pago.</p>`:`<div class="card"><strong>Pago recibido: ${money(amount())}</strong><p class="muted">Venta de contado sin alumno. No cambia ninguna deuda anterior.</p></div>`}<div class="actions">${button('Volver','render()','secondary')}${button('Confirmar y guardar','finishSale()')}</div>`;}
async function finishSale(){const event={id:saleToken,kind:mode,student:mode==='sale'?selected:null,items:items(),date:operationDate(),occurredAt:new Date().toISOString()};await commit(draft=>CafeDemo.post(draft,event),()=>{cart={};tab='Venta';},'Venta guardada en este dispositivo.');}
function accountsScreen(){let list=s.students.filter(a=>(group==='all'||a.group===group)&&(filter==='all'||CafeDemo.balance(s,a.id)>0));return title('Preparar cuentas','¿Quién tiene pendiente?')+`<div class="two"><div><label>Grado y grupo</label><select onchange="group=this.value;render()"><option value="all" ${group==='all'?'selected':''}>Todos</option>${[...new Set(s.students.map(a=>a.group))].sort().map(g=>`<option ${group===g?'selected':''}>${g}</option>`).join('')}</select></div><div><label>Mostrar</label><select onchange="filter=this.value;render()"><option value="pending">Con saldo pendiente</option><option value="all" ${filter==='all'?'selected':''}>Todos los alumnos</option></select></div></div><p class="muted">Saldos acumulados al momento de la consulta.</p>${list.map(a=>`<button class="student" onclick="openAccount('${a.id}')"><span class="line"><strong>${esc(a.name)}</strong><span class="${CafeDemo.balance(s,a.id)>0?'debt':'credit'}">${saldo(CafeDemo.balance(s,a.id))}</span></span><span class="muted">${esc(a.group)} · Ver cuenta y preparar documento</span></button>`).join('')||'<div class="card">No hay cuentas pendientes con este filtro.</div>'}<p class="notice">Cada alumno tiene su propia cuenta y documento, aunque comparta tutor con un hermano.</p>`;}
function openAccount(id){selected=id;tab='Cuenta';render();note('')}
function accountRows(id){const a=s.students.find(x=>x.id===id);return [{label:'Saldo inicial',amount:a.opening},...s.events.filter(e=>e.student===id&&e.kind!=='cash').map(e=>({label:(e.kind==='sale'?e.items.map(p=>p.qty+' × '+p.name).join(', '):'Pago / anticipo')+' · '+e.date,amount:e.kind==='sale'?e.total:-e.total}))]}
function accountScreen(){const a=student(),b=CafeDemo.balance(s,selected);return title(esc(a.group),esc(a.name))+`<div class="card"><span class="muted">Saldo al corte</span><div class="bigbalance ${b>0?'debt':'credit'}">${money(Math.abs(b))}</div><strong>${b>0?'Por pagar':b<0?'A favor':'Al corriente'}</strong></div><div class="two">${button('Registrar pago / anticipo',"paymentToken=token();nav('Pago')")}${button('Ver documento',"makeDoc()",'secondary')}</div><div class="card"><h2>Movimientos</h2>${accountRows(selected).map(r=>`<div class="row"><span>${esc(r.label)}</span><strong>${r.amount<0?'−':''}${money(Math.abs(r.amount))}</strong></div>`).join('')}</div>${button('Volver a cuentas',"nav('Cuentas')",'plain')}`;}
function paymentScreen(){return title('Pago o anticipo',esc(student().name))+`<p class="muted">Hoy: ${saldo(CafeDemo.balance(s,selected))}.</p><label for="paymentAmount">Importe recibido (${s.config.currency})</label><input id="paymentAmount" type="number" min="0.01" step="0.01" placeholder="Ejemplo: 60.00"><label>Método</label><select id="payMethod"><option>Efectivo</option><option>Transferencia confirmada por el operador</option></select><p class="notice">El pago cubre cargos antiguos primero. Si sobra dinero, queda a favor de este alumno.</p><div class="actions">${button('Volver',"nav('Cuenta')",'secondary')}${button('Revisar pago','reviewPayment()')}</div>`;}
function reviewPayment(){let raw=$('paymentAmount').value;if(!/^\d+(\.\d{1,2})?$/.test(raw)||Number(raw)<=0){note('Introduce un importe mayor que cero, con hasta dos decimales.');return}let cents=Math.round(Number(raw)*100);if(!Number.isSafeInteger(cents)){note('Revisa el importe.');return}const before=CafeDemo.balance(s,selected),method=$('payMethod').value;$('screen').innerHTML=title('Antes de confirmar','Revisar pago')+`<p>${esc(student().name)} · ${esc(student().group)}</p><div class="card"><div class="row"><span>Recibido</span><strong>${money(cents)}</strong></div><div class="row"><span>Antes</span><strong>${saldo(before)}</strong></div><div class="row"><span>Después</span><strong>${saldo(before-cents)}</strong></div><p class="muted">${esc(method)}</p></div><div class="actions">${button('Corregir',"nav('Pago')",'secondary')}${button('Confirmar y guardar',`finishPayment(${cents})`)}</div>`;}
async function finishPayment(n){const event={id:paymentToken,kind:'payment',student:selected,total:n,date:operationDate(),occurredAt:new Date().toISOString()};await commit(draft=>CafeDemo.post(draft,event),()=>{tab='Cuenta';},'Pago guardado en este dispositivo.');}
function makeDoc(){const a=student();doc={name:a.name,group:a.group,rows:accountRows(selected),balance:CafeDemo.balance(s,selected)};tab='Documento';render();note('')}
function documentScreen(){if(!doc)return '';return title('Vista previa','Cuenta individual')+`<p class="muted">Cuenta acumulada del alumno; el PDF final tendrá periodo y folio. En esta maqueta puedes imprimir la vista o guardarla como PDF desde el navegador.</p><article class="paper" id="paper"><span class="eyebrow">${esc(s.config.name)} · VISTA PREVIA</span><h2>Resumen de cuenta</h2><strong>${esc(doc.name)}</strong><p>${esc(doc.group)} · Moneda: ${s.config.currency}<br>Movimientos acumulados<br>Consulta: ${esc(operationDate())}<br>Vista previa sin folio de emisión</p><table><thead><tr><th>Movimiento</th><th>Importe</th></tr></thead><tbody>${doc.rows.map(r=>`<tr><td>${esc(r.label)}</td><td>${r.amount<0?'−':''}${money(Math.abs(r.amount))}</td></tr>`).join('')}</tbody></table><div class="row"><strong>${doc.balance>0?'Saldo por pagar':doc.balance<0?'Saldo a favor':'Saldo'}</strong><span class="total">${money(Math.abs(doc.balance))}</span></div><p class="small">Vista previa de pruebas. No es factura.</p></article><div class="actions">${button('Volver',"nav('Cuenta')",'secondary')}${button('Imprimir / guardar PDF','window.print()')}</div><p class="notice">La descarga directa y el botón para compartir el archivo desde el teléfono se implementarán en la versión operativa.</p>`;}
function studentsScreen(){return title('Organizar alumnos','Alumnos y grupos')+s.students.map(a=>`<button class="student" onclick="openAccount('${a.id}')"><strong>${esc(a.name)}</strong><br><span class="muted">${esc(a.group)} · Cuenta independiente</span></button>`).join('')+`<div class="card"><h2>Agregar alumno</h2><label>Nombre</label><input id="newName" placeholder="Nombre del alumno (para esta prueba usa datos ficticios)"><label>Grupo</label><input id="newGroup" placeholder="Ejemplo: 1° B"><div class="actions">${button('Guardar alumno','addStudent()')}</div></div>`;}
async function addStudent(){let name=$('newName').value.trim();if(!name||!$('newGroup').value.trim()){note('Escribe nombre y grupo.');return}const alumno={id:token(),name,group:$('newGroup').value.trim(),opening:0};await commit(draft=>{draft.students.push(alumno);},()=>{if(!selected)selected=alumno.id;},'Alumno guardado en este dispositivo.');}
function menuScreen(){return title('Catálogo','Menú de venta')+`<p class="muted">Agrega tus productos y precios. El inventario queda para otra etapa.</p><div class="card">${s.products.map(p=>`<div class="row"><strong>${esc(p.name)}</strong><span>${money(p.price)}</span></div>`).join('')}</div><div class="card"><h2>Agregar producto</h2><label>Nombre</label><input id="newProduct" placeholder="Ejemplo: Agua"><label>Precio (${s.config.currency})</label><input id="newPrice" type="number" min="0.01" step="0.01"><div class="actions">${button('Guardar producto','addProduct()')}</div></div>`;}
async function addProduct(){const name=$('newProduct').value.trim(),raw=$('newPrice').value,price=Math.round(Number(raw)*100);if(!name||!/^\d+(\.\d{1,2})?$/.test(raw)||!Number.isSafeInteger(price)||price<=0){note('Revisa nombre y precio positivo con hasta dos decimales.');return}const producto={id:token(),name,price};await commit(draft=>{draft.products.push(producto);},()=>{},'Producto guardado en este dispositivo.');}
function reportsScreen(){let x=CafeDemo.summary(s);return title('Revisar la operación','Ventas y cobros')+`<p class="muted">Totales acumulados de esta instalación. Los saldos iniciales no son ventas ni cobros.</p><div class="summary"><div class="card"><span class="muted">Vendido</span><div class="total">${money(x.sales)}</div></div><div class="card"><span class="muted">Cobrado</span><div class="total">${money(x.receipts)}</div></div></div><div class="card"><h2>Qué significa cada total</h2><p>Las compras entran en ventas. Los pagos y anticipos entran en cobros. Cobrar una deuda no vuelve a contar como venta.</p></div><div class="card"><h2>Movimientos registrados</h2>${s.events.map(e=>`<div class="row"><span>${e.kind==='cash'?'Venta pagada':e.kind==='sale'?'Venta a cuenta':'Pago / anticipo'}<br><span class="muted">${e.student?esc(s.students.find(a=>a.id===e.student).name):'Sin alumno'}</span></span><strong>${money(e.total)}</strong></div>`).join('')||'<p class="muted">Todavía no has registrado movimientos.</p>'}</div>`;}
function operationDate(){return new Intl.DateTimeFormat('es-MX',{dateStyle:'medium',timeZone:s.config.timezone}).format(new Date());}
function settingsScreen(){const c=s.config;return title('Cafetería · beta 0.3.0','Configuración')+`<p class="notice">Prueba de desarrollo: aún falta acceso privado y respaldo. Usa datos ficticios.</p><label>Nombre de la cafetería</label><input id="businessName" value="${esc(c.name)}" placeholder="Nombre de tu cafetería de prueba"><label>Moneda</label><select id="currency" ${s.events.length?'disabled':''}>${['MXN','USD'].map(x=>`<option ${c.currency===x?'selected':''}>${x}</option>`).join('')}</select><label>Zona horaria</label><select id="timezone" ${s.events.length?'disabled':''}>${['America/Mexico_City','America/Chicago','America/New_York','America/Los_Angeles'].map(x=>`<option ${c.timezone===x?'selected':''}>${x}</option>`).join('')}</select><label>Ciclo escolar</label><input id="cycle" value="${esc(c.cycle)}" placeholder="Ejemplo: 2026–2027"><div class="actions">${button('Guardar configuración','saveSettings()')}</div><div class="card"><h2>Datos en este dispositivo</h2><p>${s.students.length} alumnos · ${s.products.length} productos · ${s.events.length} movimientos</p><p>Versión de datos: ${revision}</p><p>Respaldo en IONOS: todavía sin conectar.</p></div>${button('Proteger guardado local','protectStorage()','secondary')}<p class="muted">Un teléfono de captura. El guardado depende de este navegador; borrar sus datos elimina esta copia. Moneda y zona horaria se fijan al registrar el primer movimiento.</p>`;}
async function saveSettings(){const name=$('businessName').value.trim(),currency=$('currency').value,timezone=$('timezone').value,cycle=$('cycle').value.trim();if(!name||!cycle){note('Escribe nombre y ciclo escolar.');return;}await commit(draft=>{if(draft.events.length&&(currency!==draft.config.currency||timezone!==draft.config.timezone))throw Error('La moneda y zona horaria ya tienen movimientos.');draft.config={name,currency,timezone,cycle,initialized:true};},()=>{tab='Menú';},'Configuración guardada. Ahora agrega productos.');}
const localStore=CafeStorage.create(globalThis.indexedDB);
function status(t){$('saveStatus').textContent=t;}
async function commit(change,after,message){
 if(!ready||busy)return;busy=true;status('Guardando…');
 try{const result=await localStore.update(change,CafeDemo.seed);s=result.state;revision=result.revision;after();render();note(result.changed?message:'La operación ya estaba guardada.');status('Guardado en este dispositivo');}
 catch(e){note('No se guardó: '+e.message);status('Error de guardado · vuelve a intentar');}
 finally{busy=false;}
}
async function protectStorage(){try{const ok=await globalThis.navigator?.storage?.persist?.();note(ok?'El navegador concedió protección de almacenamiento. Aún falta el respaldo.':'El navegador no concedió protección. El respaldo sigue pendiente.');}catch(e){note('No se pudo solicitar protección de almacenamiento.');}}
async function initialize(){status('Abriendo datos…');
 try{const r=await localStore.load(CafeDemo.seed);s=r.state;revision=r.revision;selected=s.students[0]?.id;ready=true;tab=s.config.initialized?'Venta':'Ajustes';render();status('Guardado local disponible');}
 catch(e){storageError=e.message;status('Guardado no disponible');$('screen').innerHTML=title('No se pudo abrir el guardado','Captura detenida')+'<p>'+esc(storageError)+'</p><p>No se han reemplazado los datos existentes. Vuelve a abrir esta app en el mismo navegador.</p>';}
}
const initialized=initialize();
