const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const Engine=require('./engine.js'),Storage=require('./storage.js'),fake=require('./idb-test-double.cjs');
async function setup(idb=fake()){const nodes={};const ctx={console,Intl,Math,Date,indexedDB:idb,CafeDemo:Engine,CafeStorage:Storage,window:{print(){}},document:{getElementById(id){return nodes[id]??={innerHTML:'',textContent:'',value:''};}}};vm.createContext(ctx);vm.runInContext(fs.readFileSync(__dirname+'/app.js','utf8'),ctx);await vm.runInContext('initialized',ctx);return {nodes,run:s=>vm.runInContext(s,ctx)};}
async function configured(idb){const x=await setup(idb);x.run("$('businessName').value='Cafetería de prueba';$('currency').value='MXN';$('timezone').value='America/Mexico_City';$('cycle').value='2026–2027'");await x.run('saveSettings()');return x;}
async function product(x){x.run("nav('Menú');$('newProduct').value='Burrito';$('newPrice').value='25.00';$('productCategory').value='food';$('newDescription').value=''");await x.run('addProduct()');}
async function alumno(x){x.run("nav('Alumnos');$('newLevel').value='primaria';$('newSurnames').value='Pérez';$('newName').value='Alumno de prueba';$('newGrade').value='1';$('newGroup').value='B'");await x.run('addStudent()');}
test('instalación nueva sin alumnos, productos ni movimientos y configuración requerida',async()=>{const x=await setup();assert.equal(x.run('s.students.length+s.products.length+s.events.length'),0);assert.match(x.nodes.screen.innerHTML,/Configuración/);x.run("nav('Venta')");assert.match(x.nodes.toast.textContent,/Primero/);});
test('configuración, producto, alumno, venta y pago se recuperan al reabrir',async()=>{const idb=fake(),x=await configured(idb);await product(x);await alumno(x);x.run("nav('Venta');add(s.products[0].id,2);prepareSale();mode='sale';showSaleConfirmation()");await x.run('finishSale()');assert.equal(x.run('CafeDemo.balance(s,selected)'),5000);x.run("paymentToken=token()");await x.run('finishPayment(6000)');const y=await setup(idb);assert.equal(y.run("s.config.name"),'Cafetería de prueba');assert.equal(y.run('CafeDemo.balance(s,s.students[0].id)'),-1000);assert.equal(y.run('s.events.length'),2);assert.equal(y.run('CafeDemo.summary(s).sales'),5000);assert.equal(y.run('CafeDemo.summary(s).receipts'),6000);assert.match(y.run('s.events[0].occurredAt'),/^\d{4}-/);});
test('contado puede operar sin alumnos y error de guardado conserva carrito',async()=>{const idb=fake(),x=await configured(idb);await product(x);x.run("nav('Venta');add(s.products[0].id,1);prepareSale()");idb.failNext();await x.run('finishSale()');assert.equal(x.run('amount()'),2500);assert.match(x.nodes.toast.textContent,/No se guardó/);await x.run('finishSale()');await x.run('finishSale()');assert.equal(x.run('s.events.length'),1);});
test('no permite cambiar moneda o zona horaria con movimientos',async()=>{const x=await configured();await product(x);x.run("nav('Venta');add(s.products[0].id,1);prepareSale()");await x.run('finishSale()');x.run("nav('Ajustes');$('businessName').value='Prueba';$('currency').value='USD';$('timezone').value='America/Chicago';$('cycle').value='2026'");await x.run('saveSettings()');assert.equal(x.run('s.config.currency'),'MXN');assert.match(x.nodes.toast.textContent,/ya tienen movimientos/);});
test('alumnos recién añadidos seleccionables; grupos libres y texto escapado',async()=>{const x=await configured();await product(x);x.run("nav('Alumnos');$('newLevel').value='primaria';$('newSurnames').value='Pérez';$('newName').value='<img src=x>';$('newGrade').value='3';$('newGroup').value='C'");await x.run('addStudent()');assert.match(x.nodes.screen.innerHTML,/&lt;img/);x.run("nav('Reportes');accountFilter='all';render()");assert.match(x.nodes.screen.innerHTML,/3° C/);x.run("nav('Venta');add(s.products[0].id,1);prepareSale();mode='sale';showSaleConfirmation()");await x.run('finishSale()');assert.equal(x.run('CafeDemo.balance(s,selected)'),2500);});

test('escuela, ubicación y categoría propia se conservan al reabrir; desaparece navegación Cuentas',async()=>{const idb=fake(),x=await setup(idb);x.run("$('businessName').value='Café';$('currency').value='MXN';$('timezone').value='America/Mexico_City';$('cycle').value='2026';$('schoolName').value='Escuela de prueba';$('locationName').value='Veracruz'");await x.run('saveSettings()');x.run("$('newCategory').value='Desayunos'");await x.run('addCategory()');x.run("$('newCategory').value='desayunos'");await x.run('addCategory()');assert.match(x.nodes.toast.textContent,/ya existe/);const y=await setup(idb);assert.equal(y.run('s.config.school'),'Escuela de prueba');assert.equal(y.run('s.config.location'),'Veracruz');assert.equal(y.run("s.categories.filter(c=>c.name==='Desayunos').length"),1);assert.doesNotMatch(y.nodes.nav.innerHTML,/>Cuentas</);y.run("nav('Reportes')");assert.match(y.nodes.screen.innerHTML,/Crédito pendiente/);});

test('contado asociado a alumno aparece en filtro sin cambiar su deuda',async()=>{const x=await configured();await product(x);await alumno(x);x.run("nav('Venta');add(s.products[0].id,1);prepareSale();cashStudent=selected");await x.run('finishSale()');assert.equal(x.run('CafeDemo.balance(s,selected)'),0);assert.equal(x.run("CafeDemo.report(s,{student:selected,kind:'cash'}).receipts"),2500);});

test('nivel y apellidos son requeridos para alumnos nuevos; campos separados se recuperan',async()=>{const idb=fake(),x=await configured(idb);x.run("nav('Alumnos');$('newName').value='Ana María';$('newSurnames').value='';$('newLevel').value='';$('newGrade').value='1';$('newGroup').value='A'");await x.run('addStudent()');assert.equal(x.run('s.students.length'),0);x.run("$('newSurnames').value='López Pérez';$('newLevel').value='secundaria'");await x.run('addStudent()');const y=await setup(idb);assert.equal(y.run('s.students[0].firstName'),'Ana María');assert.equal(y.run('s.students[0].surnames'),'López Pérez');assert.equal(y.run('s.students[0].name'),'Ana María López Pérez');assert.equal(y.run("CafeDemo.report(s,{search:'pérez',level:'secundaria'}).accounts.length"),1);});
test('actualizar alumno anterior conserva ID, movimientos y saldo; no adivina nivel ni divide nombre',async()=>{const idb=fake(),x=await configured(idb);await product(x);await alumno(x);x.run("nav('Venta');add(s.products[0].id,1);prepareSale();mode='sale'");await x.run('finishSale()');await x.run("commit(d=>{delete d.students[0].firstName;delete d.students[0].surnames;delete d.students[0].level;},()=>{},'')");const before=x.run('JSON.stringify(s.events)'),id=x.run('selected');x.run('editStudent(selected)');assert.equal(x.run('s.students[0].level'),undefined);assert.equal(x.run('s.students[0].name'),'Alumno de prueba Pérez');x.run("$('editFirstName').value='Alumno de prueba';$('editSurnames').value='Pérez';$('editLevel').value='kinder';$('editGrade').value='1';$('editGroup').value='B'");await x.run('saveStudentDetails()');const y=await setup(idb);assert.equal(y.run('s.students[0].id'),id);assert.equal(y.run('JSON.stringify(s.events)'),before);assert.equal(y.run('CafeDemo.balance(s,s.students[0].id)'),2500);assert.equal(y.run('s.students[0].level'),'kinder');});

test('editar precio/categoría conserva venta original y nuevo precio se usa en venta siguiente',async()=>{const idb=fake(),x=await configured(idb);await product(x);x.run("nav('Venta');add(s.products[0].id,1);prepareSale()");await x.run('finishSale()');const old=x.run('JSON.stringify(s.events)');x.run("editProduct(s.products[0].id);$('editProductName').value='Burrito nuevo';$('editDescription').value='Carne';$('editCategory').value='snacks';$('editPrice').value='30.00'");await x.run('saveProductDetails()');assert.equal(x.run('JSON.stringify(s.events)'),old);x.run("nav('Venta');add(s.products[0].id,1);prepareSale()");await x.run('finishSale()');const y=await setup(idb);assert.equal(y.run('s.events[0].items[0].price'),2500);assert.equal(y.run('s.events[1].items[0].price'),3000);assert.equal(y.run('s.products[0].categoryId'),'snacks');});
test('eliminar requiere confirmación; fallo no retira producto; restaurar mantiene ID y ventas',async()=>{const idb=fake(),x=await configured(idb);await product(x);const id=x.run('s.products[0].id');x.run("requestRemove('product',s.products[0].id)");assert.equal(x.run('!!s.products[0].archived'),false);idb.failNext();await x.run('confirmRemove()');assert.equal(x.run('!!s.products[0].archived'),false);await x.run('confirmRemove()');assert.equal(x.run('s.products[0].archived'),true);x.run("nav('Venta')");assert.doesNotMatch(x.nodes.screen.innerHTML,/Burrito/);const y=await setup(idb);assert.equal(y.run('s.products[0].archived'),true);await y.run("restoreItem('product',s.products[0].id)");assert.equal(y.run('s.products[0].id'),id);assert.equal(y.run('s.products[0].archived'),false);});
test('alumno retirado conserva deuda cobrable y reportes; no admite nuevas ventas',async()=>{const idb=fake(),x=await configured(idb);await product(x);await alumno(x);const id=x.run('selected');x.run("nav('Venta');add(s.products[0].id,1);prepareSale();mode='sale'");await x.run('finishSale()');x.run("requestRemove('student',selected)");await x.run('confirmRemove()');assert.equal(x.run('activeStudents().length'),0);assert.equal(x.run('CafeDemo.report(s).debt'),2500);x.run(`openAccount('${id}');paymentToken=token()`);await x.run('finishPayment(2500)');assert.equal(x.run('CafeDemo.balance(s,selected)'),0);assert.throws(()=>x.run("CafeDemo.post(s,{id:'forbidden',student:selected,kind:'sale',items:[{price:100,qty:1}]})"),/retirado/);const y=await setup(idb);assert.equal(y.run('s.students[0].archived'),true);assert.equal(y.run('s.events.length'),2);});
test('editar grado/grupo cambia agrupación conservando cuenta; jerarquía por nivel y grupo cerrada al entrar',async()=>{const x=await configured();await alumno(x);x.run('editStudent(selected)');x.run("$('editFirstName').value='Ana';$('editSurnames').value='Pérez';$('editLevel').value='secundaria';$('editGrade').value='2';$('editGroup').value='C'");await x.run('saveStudentDetails()');assert.equal(x.run('s.students[0].group'),'2° C');assert.match(x.nodes.screen.innerHTML,/<summary><strong>Secundaria/);assert.match(x.nodes.screen.innerHTML,/<summary><strong>2° C/);assert.doesNotMatch(x.nodes.screen.innerHTML,/<details[^>]* open/);assert.match(x.nodes.screen.innerHTML,/>Editar</);assert.match(x.nodes.screen.innerHTML,/>Eliminar</);});

test('cuenta desde Reportes no permite editar datos; edición exclusivamente en Alumnos',async()=>{const x=await configured();await alumno(x);x.run("nav('Reportes');openAccount(s.students[0].id)");assert.doesNotMatch(x.nodes.screen.innerHTML,/<input|<select|Guardar datos del alumno|saveStudentDetails|requestRemove/);assert.match(x.nodes.screen.innerHTML,/Registrar pago/);assert.match(x.nodes.screen.innerHTML,/Ver documento/);const before=x.run('JSON.stringify(s.students)');await x.run('saveStudentDetails()');assert.equal(x.run('JSON.stringify(s.students)'),before);assert.match(x.nodes.toast.textContent,/Alumnos/);x.run('editStudent(s.students[0].id)');assert.match(x.nodes.screen.innerHTML,/editFirstName/);assert.match(x.nodes.screen.innerHTML,/Guardar cambios/);x.run('openAccount(s.students[0].id);makeDoc()');assert.match(x.nodes.screen.innerHTML,/Imprimir \/ guardar PDF/);});
