const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const Engine=require('./engine.js'),Storage=require('./storage.js'),fake=require('./idb-test-double.cjs');
async function setup(idb=fake()){const nodes={};const ctx={console,Intl,Math,Date,indexedDB:idb,CafeDemo:Engine,CafeStorage:Storage,window:{print(){}},document:{getElementById(id){return nodes[id]??={innerHTML:'',textContent:'',value:''};}}};vm.createContext(ctx);vm.runInContext(fs.readFileSync(__dirname+'/app.js','utf8'),ctx);await vm.runInContext('initialized',ctx);return {nodes,run:s=>vm.runInContext(s,ctx)};}
async function configured(idb){const x=await setup(idb);x.run("$('businessName').value='Cafetería de prueba';$('currency').value='MXN';$('timezone').value='America/Mexico_City';$('cycle').value='2026–2027'");await x.run('saveSettings()');return x;}
async function product(x){x.run("nav('Menú');$('newProduct').value='Burrito';$('newPrice').value='25.00'");await x.run('addProduct()');}
async function alumno(x){x.run("nav('Alumnos');$('newName').value='Alumno de prueba';$('newGroup').value='1° B'");await x.run('addStudent()');}
test('instalación nueva sin alumnos, productos ni movimientos y configuración requerida',async()=>{const x=await setup();assert.equal(x.run('s.students.length+s.products.length+s.events.length'),0);assert.match(x.nodes.screen.innerHTML,/Configuración/);x.run("nav('Venta')");assert.match(x.nodes.toast.textContent,/Primero/);});
test('configuración, producto, alumno, venta y pago se recuperan al reabrir',async()=>{const idb=fake(),x=await configured(idb);await product(x);await alumno(x);x.run("nav('Venta');add(s.products[0].id,2);prepareSale();mode='sale';showSaleConfirmation()");await x.run('finishSale()');assert.equal(x.run('CafeDemo.balance(s,selected)'),5000);x.run("paymentToken=token()");await x.run('finishPayment(6000)');const y=await setup(idb);assert.equal(y.run("s.config.name"),'Cafetería de prueba');assert.equal(y.run('CafeDemo.balance(s,s.students[0].id)'),-1000);assert.equal(y.run('s.events.length'),2);assert.equal(y.run('CafeDemo.summary(s).sales'),5000);assert.equal(y.run('CafeDemo.summary(s).receipts'),6000);assert.match(y.run('s.events[0].occurredAt'),/^\d{4}-/);});
test('contado puede operar sin alumnos y error de guardado conserva carrito',async()=>{const idb=fake(),x=await configured(idb);await product(x);x.run("nav('Venta');add(s.products[0].id,1);prepareSale()");idb.failNext();await x.run('finishSale()');assert.equal(x.run('amount()'),2500);assert.match(x.nodes.toast.textContent,/No se guardó/);await x.run('finishSale()');await x.run('finishSale()');assert.equal(x.run('s.events.length'),1);});
test('no permite cambiar moneda o zona horaria con movimientos',async()=>{const x=await configured();await product(x);x.run("nav('Venta');add(s.products[0].id,1);prepareSale()");await x.run('finishSale()');x.run("nav('Ajustes');$('businessName').value='Prueba';$('currency').value='USD';$('timezone').value='America/Chicago';$('cycle').value='2026'");await x.run('saveSettings()');assert.equal(x.run('s.config.currency'),'MXN');assert.match(x.nodes.toast.textContent,/ya tienen movimientos/);});
test('alumnos recién añadidos seleccionables; grupos libres y texto escapado',async()=>{const x=await configured();await product(x);x.run("nav('Alumnos');$('newName').value='<img src=x>';$('newGroup').value='3° C'");await x.run('addStudent()');assert.match(x.nodes.screen.innerHTML,/&lt;img/);x.run("nav('Cuentas');filter='all';render()");assert.match(x.nodes.screen.innerHTML,/3° C/);x.run("nav('Venta');add(s.products[0].id,1);prepareSale();mode='sale';showSaleConfirmation()");await x.run('finishSale()');assert.equal(x.run('CafeDemo.balance(s,selected)'),2500);});
