(function(root){'use strict';
const clone=v=>v===undefined?undefined:JSON.parse(JSON.stringify(v));
function create(indexedDB,name,seed,validate,crypto=root.crypto){
 let dbPromise,key=null,salt=null;
 const enc=new TextEncoder(),dec=new TextDecoder(),hex=v=>Array.from(v,x=>x.toString(16).padStart(2,'0')).join(''),bytes=v=>{if(typeof v!=='string'||! /^[a-f0-9]+$/.test(v)||v.length%2)throw Error('Copia cifrada inválida.');return Uint8Array.from(v.match(/../g),x=>parseInt(x,16));};
 function open(){return dbPromise??=new Promise((resolve,reject)=>{if(!indexedDB)return reject(Error('No se permite guardar en este navegador.'));const req=indexedDB.open(name,1);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains('state'))req.result.createObjectStore('state');};req.onerror=()=>reject(req.error);req.onblocked=()=>reject(Error('Cierra las pestañas anteriores.'));req.onsuccess=()=>resolve(req.result);});}
 async function read(){const db=await open();return new Promise((resolve,reject)=>{let data;const tx=db.transaction('state','readonly'),req=tx.objectStore('state').get('current');req.onsuccess=()=>data=clone(req.result);tx.oncomplete=()=>resolve(data);tx.onabort=()=>reject(tx.error||Error('No se pudo leer la copia local.'));tx.onerror=()=>{};});}
 async function cas(old,value){const db=await open();return new Promise((resolve,reject)=>{let error;const tx=db.transaction('state','readwrite'),store=tx.objectStore('state'),req=store.get('current');req.onsuccess=()=>{if(JSON.stringify(req.result)!==JSON.stringify(old)){error=Error('Hay cambios en otra pestaña. Recarga y desbloquea antes de continuar.');tx.abort();return;}store.clear();store.put(value,'current');};tx.oncomplete=resolve;tx.onabort=()=>reject(error||tx.error||Error('No se guardó la copia cifrada.'));tx.onerror=()=>{};});}
 async function derive(password,s){if(typeof password!=='string'||password.length<12||password.length>256)throw Error('Usa una clave local de 12 a 256 caracteres.');if(!crypto?.subtle)throw Error('Se necesita HTTPS y cifrado disponible.');const material=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt:s,iterations:600000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
 async function decrypt(envelope){if(!key)throw Error('Desbloquea los datos del teléfono.');if(envelope?.vaultVersion!==1||envelope.salt!==hex(salt))throw Error('Copia cifrada inválida o clave cambiada.');try{const iv=bytes(envelope.iv);if(iv.length!==12)throw Error();const raw=await crypto.subtle.decrypt({name:'AES-GCM',iv,additionalData:enc.encode('task-fixer-vault-v1:'+name)},key,bytes(envelope.cipher));const payload=JSON.parse(dec.decode(raw));validate(payload.record);return payload;}catch(e){throw Error('Clave local incorrecta o copia dañada. No se cambió ningún dato.');}}
 async function encrypt(payload){if(!key)throw Error('Datos bloqueados.');const iv=crypto.getRandomValues(new Uint8Array(12)),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:enc.encode('task-fixer-vault-v1:'+name)},key,enc.encode(JSON.stringify(payload)));return {vaultVersion:1,salt:hex(salt),iv:hex(iv),cipher:hex(new Uint8Array(cipher))};}
 async function unlock(password){const old=await read();salt=old?.vaultVersion===1?bytes(old.salt):crypto.getRandomValues(new Uint8Array(16));if(salt.length!==16)throw Error('Copia cifrada inválida.');key=await derive(password,salt);try{if(old?.vaultVersion===1)return clone((await decrypt(old)).record);const record=old===undefined?{schema:3,revision:1,state:clone(seed())}:validate(old);if(record.schema!==3)throw Error('Actualiza primero a 0.6.0 y genera un respaldo.');const payload={record,offlineUntil:0,previous:null};const envelope=await encrypt(payload);await cas(old,envelope);return clone(record);}catch(e){key=null;salt=null;throw e;}}
 async function load(){return clone((await decrypt(await read())).record);}
 async function update(change,_seed,expected){const old=await read(),payload=await decrypt(old),r=payload.record;if(expected!==undefined&&r.revision!==expected)throw Error('Hay cambios desde otra pestaña. Recarga antes de continuar.');const draft=clone(r.state),changed=change(draft)!==false;if(!changed)return {...clone(r),changed:false};if(r.revision===Number.MAX_SAFE_INTEGER)throw Error('Revisión fuera de rango.');const next={schema:3,revision:r.revision+1,state:draft};validate(next);payload.record=next;await cas(old,await encrypt(payload));return {...clone(next),changed:true};}
 async function restore(imported,_seed,expected){validate(imported);if(imported.schema!==3)throw Error('Formato de respaldo incompatible.');const old=await read(),payload=await decrypt(old),r=payload.record;if(r.revision!==expected||r.revision===Number.MAX_SAFE_INTEGER)throw Error('La copia cambió. Revisa el respaldo de nuevo.');payload.previous=clone(r);payload.record={schema:3,revision:r.revision+1,state:clone(imported.state)};validate(payload.record);await cas(old,await encrypt(payload));return {...clone(payload.record),changed:true};}
 async function grant(until){if(!Number.isSafeInteger(until)||until<0)throw Error('Permiso offline inválido.');const old=await read(),payload=await decrypt(old);if(until!==0&&Math.abs(payload.offlineUntil-until)<60000)return;payload.offlineUntil=until;await cas(old,await encrypt(payload));}
 async function offlineAllowed(){const p=await decrypt(await read());return Number.isSafeInteger(p.offlineUntil)&&Date.now()<p.offlineUntil;}
 async function saveDraft(cart){if(!cart||typeof cart!=='object'||Array.isArray(cart)||Object.entries(cart).some(([id,q])=>! /^[a-zA-Z0-9_-]+$/.test(id)||!Number.isSafeInteger(q)||q<1||q>1000000))throw Error('Borrador inválido.');const old=await read(),payload=await decrypt(old);payload.draft=clone(cart);await cas(old,await encrypt(payload));}
 async function takeDraft(){const old=await read(),payload=await decrypt(old),draft=clone(payload.draft||{});if(payload.draft){delete payload.draft;await cas(old,await encrypt(payload));}return draft;}
 return {exists:async()=>(await read())?.vaultVersion===1,unlock,load,update,restore,grant,offlineAllowed,saveDraft,takeDraft,lock(){key=null;salt=null;},name};
}
const api={create};if(typeof module!=='undefined')module.exports=api;else root.CafeVault=api;
})(globalThis);
